name: otp_timer_button
description: This package for easy implementation otp timer button which will be enabled after specified time.
version: 1.1.1
homepage: https://github.com/mpcreza/otp_timer_button

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
